### ISSUE TITLE
TableView not being updated until parsing is done.

### ISSUE THREAD

**Issue by tychop** [AlanQuatermain/ParserExample#1]
I'm not sure if this problem is actually an issue for this example, but the tableView in this example is not being updated until parsing is completely done, or until I start scrolling in the table. It's difficult to see because the xml that is parsed is short and finishes quickly, but when I use a larger xml, the 'problem' is visible: nothing is being shown until you scroll manually in the tableview, or the parsing completes (Even if I save the context after x nodes have been parsed). I can even see the tableView methods being called. I've got the same issue in a project using the same technique, and am unable to figure out how to solve this.

**Comment by AlanQuatermain** [comment]
It's because the project isn't saving the managed object context until it's finished parsing the entire file. I'll update it to save after each record.

**Comment by AlanQuatermain** [comment]
I've updated the project with the following changes in the TumblrParserDelegate:
- Save the managedObjectContext after parsing the opening <tumblelog> tag.
- Added a handler for the closing <post> tag which saves the managedObjectContext.

Together these should cause the UI to update as each post is parsed from the input XML.

**Comment by tychop** [comment]
Yes, I've already figured that out. I save the context every 10 records. But the problem still persists. The strange thing is, that when I manually scroll the empty view while the parsing is busy, the cells appear on screen...

**Comment by tychop** [comment]
You can simulate it by inserting 
printf(".");[NSThread sleepForTimeInterval:0.2];
After the [self.managedObjectContext save: NULL]; statement in the endPost method.
